plugins { id 'com.android.application' }

android {
    namespace 'com.icecam.dev'
    compileSdk 35

    defaultConfig {
        applicationId 'com.icecam.dev'
        minSdk 31
        targetSdk 35
        versionCode 942
        versionName '9.4.3-safe-root-bootstrap'
    }
}

dependencies {
    compileOnly files('libs/xposed-api-stub.jar')
}
