plugins { id 'com.android.application' }

android {
    namespace 'dev.icecam.app'
    compileSdk 35
    defaultConfig {
        applicationId 'dev.icecam.app'
        minSdk 23
        targetSdk 35
        versionCode 19
        versionName '0.19-v19-stable-backend-queue'
    }
    buildTypes {
        debug { debuggable true; minifyEnabled false }
        release { minifyEnabled false }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    packaging { jniLibs { useLegacyPackaging true } }
}
