package dev.icecam.app;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.hardware.camera2.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.zip.*;

public class MainActivity extends Activity{
 TextView status,diag; LinearLayout root;
 public void onCreate(Bundle b){super.onCreate(b); if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.CAMERA},5); build(); dumpCameras();}
 TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(0xffeef3ff);v.setTextSize(sp);v.setPadding(20,12,20,12);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void card(View v){v.setBackgroundColor(0xff111923);v.setPadding(10,10,10,10);} 
 void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,32,24,32);root.setBackgroundColor(0xff05080d);sv.addView(root);root.addView(tv("IceCam",38));root.addView(tv("System camera replacement · v3 dev hook layer",16));status=tv("Status loading",17);card(status);root.addView(status,new LinearLayout.LayoutParams(-1,-2));TextView actions=tv("Actions",28);root.addView(actions);Button rootBtn=btn("Request Root Check");root.addView(rootBtn);rootBtn.setOnClickListener(v->status.setText(Shell.run("id; icecamctl status 2>/dev/null || true")));Button prep=btn("Prepare Hook Layer");root.addView(prep);prep.setOnClickListener(v->status.setText(Shell.run("icecamctl prepare-hooks 2>&1")));Button exp=btn("Export Debug Bundle");root.addView(exp);exp.setOnClickListener(v->exportBundle());diag=tv("Diagnostics",15);card(diag);root.addView(diag,new LinearLayout.LayoutParams(-1,-2));setContentView(sv);} 
 void dumpCameras(){StringBuilder s=new StringBuilder("IceCam v3 dev ready\nHook targets: Camera1 / Camera2 / CameraX groundwork\n\n");try{CameraManager cm=(CameraManager)getSystemService(CAMERA_SERVICE);for(String id:cm.getCameraIdList()){CameraCharacteristics c=cm.getCameraCharacteristics(id);Integer face=c.get(CameraCharacteristics.LENS_FACING);Integer orient=c.get(CameraCharacteristics.SENSOR_ORIENTATION);Object level=c.get(CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL);s.append("Camera ").append(id).append(" facing=").append(face).append(" orientation=").append(orient).append(" hwLevel=").append(level).append('\n');}}catch(Throwable t){s.append("camera dump error ").append(t);}diag.setText(s.toString());}
 void exportBundle(){try{String r=Shell.run("icecamctl logs 2>&1");status.setText(r+"\nExpected: /sdcard/Download/icecam_logs.tar.gz");}catch(Throwable t){status.setText("export failed "+t);}}
}
